# NotifyMe/constants.py

Plans = {
  "BASIC_PLAN":"BASIC",
  "REGULAR_PLAN": "REGULAR",
  "STANDARD_PLAN": "STANDARD",
  "PREMIUM_PLAN": "PREMIUM"
}


PlansDuration = {
  "BASIC": 30,
  "REGULAR": 90,
  "STANDARD": 180,
  "PREMIUM": 365
}

PlansId = {
  1: "BASIC",
  2: "REGULAR",
  3: "STANDARD",
  4: "PREMIUM"
}

NotificationTypeId={
  1: "NEW FEATURE ADDED",
  2: "SESSION STARTED",
  3:"SESSION ENDED",
  4:"PRIVATE MESSAGE",
  5:"MAINTENANCE ALERT",
  6:"SUBSCRIPTION PLAN UPDATE",
  7:"GIVE SUGGESTIONS"
}

