# Generated by Django 5.0.6 on 2024-06-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotifyMe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationtype',
            old_name='n_type',
            new_name='notification_type',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration_days',
        ),
        migrations.AlterModelTable(
            name='notificationtype',
            table='ms_notification_type',
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='ms_subscription_plan',
        ),
    ]
