# Generated by Django 5.0.6 on 2024-06-14 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotifyMe', '0002_rename_n_type_notificationtype_notification_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='s_type',
            new_name='subscription_plan',
        ),
    ]
