# NotifyMe/constants.py
from enum import Enum

class Plans(Enum):
  BASIC_PLAN="BASIC"
  REGULAR_PLAN= "REGULAR"
  STANDARD_PLAN= "STANDARD"
  PREMIUM_PLAN= "PREMIUM"



class PlansDuration(Enum):
  BASIC = 30,
  REGULAR = 90,
  STANDARD = 180,
  PREMIUM = 365
  

class NotificationTypeId(Enum):
  FEATURE_INTRODUCATION = 1
  ANNOUNCEMENTS = 2
  SEND_PERSONALIZED_MESSAGES = 3
  NEW_FEATURE_ADDED = 4
  MAINTENANCE_ALERT = 5
  SUBSCRIPTION_PLAN_END_AND_UPGRADATION_NOTIFICATION = 6
  USER_FEEDBACK = 7



