from enum import Enum

class ErrorCodes(Enum):
  # USER error_codes
  HTTP_101_USER_NOT_FOUND = 101 
  HTTP_102_UNEXPECTED_ERROR_WHILE_FETCHING_USER = 102 
  HTTP_103_VALIDATION_ERROR_WHILE_CREATING_USER = 103 
  HTTP_105_INVALID_SUBSCRIPTION_ID_PROVIDED = 105 
  HTTP_106_USER_ALREADY_EXISTS = 106 
  HTTP_108_INVALID_USER_ID_PROVIDED = 108 
  HTTP_109_PERMISSION_DENIED_WHILE_UPDATING_USER_DATA = 109
  HTTP_110_MISSING_ID_WHILE_REQUESTING_FOR_UPDATE = 110 
  HTTP_111_UNEXPECTED_ERROR_OCCURED_WHILE_UPDATING_USER = 111
  HTTP_112_PERMISSION_DENIED_WHILE_DELETING_USER_DATA = 112
  HTTP_114_UNEXPECTED_ERROR_OCCURED_WHILE_DELETING_USER = 114
  HTTP_115_MISSING_ID_IN_REQUEST_FOR_USER_DELETION = 115
  HTTP_140_VALIDATION_ERROR_WHILE_UPDATING_USER = 140 
  HTTP_143_UNEXPECTED_ERROR_WHILE_CREATING_USER = 143
  HTTP_147_INTEGRITY_ERROR_WHILE_CREATING_USER = 147 
  
  # Subscription error_Codes
  
  
  HTTP_117_SUBSCRIPTION_DATA_NOT_FOUND = 117
  HTTP_118_UNEXPECTED_ERROR_WHILE_FETCHING_SUBSCRIPTION_DATA = 118
  HTTP_120_SUBSCRIPTION_DATA_ALREADY_EXISTS = 120 
  HTTP_121_VALIDATION_ERROR_WHILE_CREATING_SUBSCRIPTION_DATA = 121 
  HTTP_122_UNEXPECTED_ERROR_WHILE_CREATING_SUBSCRIPTION_DATA = 122
  HTTP_124_INVALID_SUBSCRIPTION_DATA_ID_PROVIDED = 124
  HTTP_125_VALIDATION_ERROR_WHILE_UPDATING_SUBSCRIPTION_DATA = 125 
  HTTP_126_UNEXPECTED_ERROR_WHILE_UPDATING_SUBSCRIPTION_DATA = 126
  HTTP_127_PERMISSION_DENIED_WHILE_UPDATING_SUBSCRIPTION_DATA = 127
  HTTP_129_UNEXPECTED_ERROR_WHILE_DELETING_SUBSCRIPTION_DATA = 129
  HTTP_144_DATABASE_ERROR_WHILE_RETRIEVING_ALL_SUBSCRIPTIONS = 144 
  HTTP_145_DATABASE_ERROR_WHILE_RETRIEVING_ALL_SUBSCRIPTIONS_PLANS = 145 
  
  # SubscriptionPlanAPI error_codes
  
  
  HTTP_131_SUBSCRIPTION_PLANS_NOT_FOUND = 131 
  HTTP_132_UNEXPECTED_ERROR_WHILE_FETCHING_SUBSCRIPTION_PLANS = 132
   
  HTTP_134_VALIDATION_ERROR_WHILE_CREATING_SUBSCRIPTION_PLAN = 134 
  HTTP_135_UNEXPECTED_ERROR_WHILE_CREATING_SUBSCRIPTION_PLAN = 135
  HTTP_136_INTEGRITY_ERROR_WHILE_CREATING_SUBSCRIPTION_PLAN = 136 
  HTTP_138_UNEXPECTED_ERROR_WHILE_DELETING_SUBSCRIPTION_PLAN = 138
  HTTP_139_PERMISSION_DENIED_WHILE_DELETING_SUBSCRIPTION_PLAN_DATA = 139 
  HTTP_141_FAILED_TO_RETRIEVE_ALL_USERS_FROM_DATABASE = 141
  HTTP_142_UNEXPECTED_ERROR_WHILE_RETRIEVING_ALL_USERS = 142
  HTTP_146_UNEXPECTED_ERROR_WHILE_FETCHING_SUBSCRIPTION_PLAN_BY_ID = 146
  HTTP_148_SUBSCRIPTION_PLAN_FIELD_IS_REQUIRED = 148
  HTTP_149_USER_INSTANCES_NOT_FOUND = 149
  HTTP_150_NO_DATA_IN_THE_REQUEST_GIVE_SOME_DATA = 150
  HTTP_152_SUBSCRIPTION_PLAN_INSTANCES_NOT_FOUND = 152
  HTTP_153_DATABASE_ERROR = 153 
  HTTP_154_DURATION_NOT_FOUND_ERROR_FOR_SUBSCRIPTION_PLAN_TYPE = 154 
  HTTP_155_UNEXPECTED_ERROR_OCCURED_WHILE_CALCULATING_END_DATE = 155
  HTTP_156_PERMISSION_DENIED_WHILE_DELETING_SUBSCRIPTION_DATA = 156 
  HTTP_157_USER_ID_MISSING = 157 
  HTTP_158_INVALID_SUBSCRIPTION_PLAN_PROVIDED = 158 
  HTTP_159_SUBSCRIPTION_ID_IS_MISSING = 159 
  HTTP_160_SUBSCRIPTION_PLAN_FIELD_IS_MISSING = 160 
  HTTP_161_SUBSCRIPTION_PLAN_ID_MISSING = 161 
  HTTP_162_USER_DATA_NOT_GIVEN = 162
  HTTP_163_SUBSCRIPTION_DATA_NOT_GIVEN = 163
  HTTP_164_USER_PATCH = 164
  HTTP_165_SUBSCRIPTION_PATCH = 165
  HTTP_169_DATABASE_ERROR_WHILE_RETRIEVING_ANNOUNCEMENTS = 169
  HTTP_171_NOTIFICATION_DATABASE_ERROR = 171
  HTTP_172_INTEGRITY_ERROR_WHILE_CREATING_NOTIFICATION = 172
  HTTP_174_NOTIFICATION_DELETE = 174
  HTTP_175_MISSING_ID_FOR_NOTIFICATION_DELETION = 175
  HTTP_176_NOTIFICATION_ID_MISSING = 176
  HTTP_177_PERMISSION_DENIED_WHILE_DELETING_NOTIFICATION = 177
  HTTP_182_DATABASE_NOT_FOUND = 182

class ErrorCodeMessages(Enum):
  
  HTTP_101_USER_NOT_FOUND="User Not Found"
  HTTP_102_UNEXPECTED_ERROR_WHILE_FETCHING_USER = "Unexpected error while fetching user from the Database"
  HTTP_103_VALIDATION_ERROR_WHILE_CREATING_USER = "Validation error while creating user. You need to give value for these fields. FIELDS: ( subscription_plan, email_id, first_name, last_name )"
  HTTP_105_INVALID_SUBSCRIPTION_ID_PROVIDED = "Invalid Subscription_id provided"
  HTTP_106_USER_ALREADY_EXISTS = "User Already exists"
  HTTP_108_INVALID_USER_ID_PROVIDED = "Invalid User_id provided"
  HTTP_109_PERMISSION_DENIED_WHILE_UPDATING_USER_DATA = "Permission Denied while updating user data"
  HTTP_110_MISSING_ID_WHILE_REQUESTING_FOR_UPDATE = "Missing id while requesting for update"
  HTTP_111_UNEXPECTED_ERROR_OCCURED_WHILE_UPDATING_USER = "Unexpected error occured while updating user"
  HTTP_112_PERMISSION_DENIED_WHILE_DELETING_USER_DATA = "Permission denied while deleting user data"

  HTTP_114_UNEXPECTED_ERROR_OCCURED_WHILE_DELETING_USER = "Unexpected error occured while deleting user"
  HTTP_115_MISSING_ID_IN_REQUEST_FOR_USER_DELETION = "Missing id in request for User deletion"

  HTTP_117_SUBSCRIPTION_DATA_NOT_FOUND = "Subscription data not found"
  HTTP_118_UNEXPECTED_ERROR_WHILE_FETCHING_SUBSCRIPTION_DATA = "Unexpected error while fetching Subscription data"
  HTTP_120_SUBSCRIPTION_DATA_ALREADY_EXISTS = "Subscription data already exists"
  HTTP_121_VALIDATION_ERROR_WHILE_CREATING_SUBSCRIPTION_DATA = "Validation error while creating Subscription data. You need to give value to these fields. FIELDS: ( id, user_id, subscription_plan )"
  HTTP_122_UNEXPECTED_ERROR_WHILE_CREATING_SUBSCRIPTION_DATA = "Unexpected error while creating Subscription data"
  HTTP_124_INVALID_SUBSCRIPTION_DATA_ID_PROVIDED = "Invalid Subscription data id provided"
  HTTP_125_VALIDATION_ERROR_WHILE_UPDATING_SUBSCRIPTION_DATA = "Validation error while updating Subscription data"
  HTTP_126_UNEXPECTED_ERROR_WHILE_UPDATING_SUBSCRIPTION_DATA = "Unexpected error while updating Subscription data"
  HTTP_127_PERMISSION_DENIED_WHILE_UPDATING_SUBSCRIPTION_DATA = "Permission denied while updating Subscription data"
  HTTP_129_UNEXPECTED_ERROR_WHILE_DELETING_SUBSCRIPTION_DATA = "Unexpected error while deleting Subscription data"
  HTTP_131_SUBSCRIPTION_PLANS_NOT_FOUND = "Subscription_plans not found"
  HTTP_132_UNEXPECTED_ERROR_WHILE_FETCHING_SUBSCRIPTION_PLANS = "Unexpected error while fetching Subscription_plans"
  
  HTTP_134_VALIDATION_ERROR_WHILE_CREATING_SUBSCRIPTION_PLAN = "Validation error while creating Subscription_plan"
  HTTP_135_UNEXPECTED_ERROR_WHILE_CREATING_SUBSCRIPTION_PLAN = "Unexpected error while creating Subscription_plan"
  HTTP_136_INTEGRITY_ERROR_WHILE_CREATING_SUBSCRIPTION_PLAN = "Unexpected error while creating Subscription_plan"
  HTTP_138_UNEXPECTED_ERROR_WHILE_DELETING_SUBSCRIPTION_PLAN = "Unexpected error while deleting Subscription_plan"
  HTTP_139_PERMISSION_DENIED_WHILE_DELETING_SUBSCRIPTION_PLAN_DATA = "Permission denied while deleting Subscription_plan data"
  HTTP_140_VALIDATION_ERROR_WHILE_UPDATING_USER = "Validation error while updating user. See among these fields whose value you have not given. FIELDS: < id, email_id, subscription_plan, first_name, last_name >"
  HTTP_141_FAILED_TO_RETRIEVE_ALL_USERS_FROM_DATABASE = "Failed to retrieve all users from database"
  HTTP_142_UNEXPECTED_ERROR_WHILE_RETRIEVING_ALL_USERS = "Unexpected error while retrieving all users"
  HTTP_143_UNEXPECTED_ERROR_WHILE_CREATING_USER = "Unexpected error while creating user"
  HTTP_144_DATABASE_ERROR_WHILE_RETRIEVING_ALL_SUBSCRIPTIONS = "Database error while retrieving all subscriptions"
  HTTP_145_DATABASE_ERROR_WHILE_RETRIEVING_ALL_SUBSCRIPTIONS_PLANS = "Database error while retrieving all Subscription_plans"
  HTTP_146_UNEXPECTED_ERROR_WHILE_FETCHING_SUBSCRIPTION_PLAN_BY_ID = "Unexpected error while fetching Subscription_plan by id"
  HTTP_147_INTEGRITY_ERROR_WHILE_CREATING_USER = "Integrity error while creating user"
  HTTP_148_SUBSCRIPTION_PLAN_FIELD_IS_REQUIRED = "subscription_plan field is required"
  HTTP_149_USER_INSTANCES_NOT_FOUND = "User instances not found"
  HTTP_150_NO_DATA_IN_THE_REQUEST_GIVE_SOME_DATA = "No data in the request give some data"
  HTTP_151_SUBSCRIPTION_INSTANCES_NOT_FOUND = "Subscription instances not found"
  HTTP_152_SUBSCRIPTION_PLAN_INSTANCES_NOT_FOUND = "Subscription_plan instances not found"
  HTTP_153_DATABASE_ERROR_WHILE_FETCHING_USERS = "Database error while fetching user"
  HTTP_154_DURATION_NOT_FOUND_ERROR_FOR_SUBSCRIPTION_PLAN_TYPE = "Duration not found error for Subscription_plan type"
  HTTP_155_UNEXPECTED_ERROR_OCCURED_WHILE_CALCULATING_END_DATE = "Unexpected error occured while calculating end_date"
  HTTP_156_PERMISSION_DENIED_WHILE_DELETING_SUBSCRIPTION_DATA = "Permission denied while deleting Subscription data"
  HTTP_157_USER_ID_MISSING = "User_id missing from the data"
  HTTP_158_INVALID_SUBSCRIPTION_PLAN_PROVIDED = "Invalid Subscription-Plan provided"
  HTTP_159_SUBSCRIPTION_ID_IS_MISSING = "Subscription_id is missing from the data"
  HTTP_160_SUBSCRIPTION_PLAN_FIELD_IS_MISSING = "Value in the Subscription_plan field is missing"
  HTTP_161_SUBSCRIPTION_PLAN_ID_MISSING = "Subscription-Plan id missing"
  HTTP_162_USER_DATA_NOT_GIVEN = "No data has been sent. You have to provide values to fields. FIELDS: < subscription_plan, email_id, first_name, last_name >"
  HTTP_163_SUBSCRIPTION_DATA_NOT_GIVEN = "No data has been sent. You have to provide values to fields. FIELDS: < user_id, subscription_plan >"
  HTTP_164_USER_PATCH = "No data given. You have to provide values to fields. FIELDS: Mandatory_Field: < email_id >, Field whose value you want to change: < subscription_plan, first_name, last_name>"
  HTTP_165_SUBSCRIPTION_DATA_PATCH = "No data given. You have to provide values to fields. FIELDS: Mandatory_Field: user_id, Field whose value you want to change: < subscription_plan >"
  HTTP_166_USER_DELETE = "No data has been sent. Provide value to field. FIELD: id"
  HTTP_167_SUBSCRIPTION_DATA_DELETE = "No data has been sent. Provide value to field. FIELD: id"
  HTTP_168_SUBSCRIPTION_PLAN_DATA_NOT_GIVEN = "No data given. You have to provide value to field. FIELDS: subscription_plan"
  HTTP_169_DATABASE_ERROR_WHILE_RETRIEVING_ANNOUNCEMENTS = "Database error while fetching Announcements"
  HTTP_170_ANNOUNCEMETS_FETCHED_SUCCESSFULY = "Announcements fetched successfully"
  HTTP_171_NOTIFICATION_DATABASE_ERROR = "Failed to create notification object. ERROR: Notification database doesnot exist"
  HTTP_172_INTEGRITY_ERROR_WHILE_CREATING_NOTIFICATION = "Failed to create notification object. Give data to fields. FIELDS: ( title, message, notification_type )"
  HTTP_181_NOTIFICATION_DATA_NOT_GIVEN = "No data given. You have to provide value to fields. FIELDS: ( notification_type, title, message )"
  HTTP_174_NOTIFICATION_DATA_NOT_GIVEN = "No data given. You have to provide value to field. FIELDS: ( notification_type, title, message)"
  HTTP_174_NOTIFICATION_DELETE = "No data has been sent. Provide value to field. FIELD: id"
  HTTP_175_MISSING_ID_FOR_NOTIFICATION_DELETION = "Missing id for Notification Deletion"
  HTTP_176_NOTIFICATION_ID_MISSING = "id missing from the data"
  HTTP_177_PERMISSION_DENIED_WHILE_DELETING_NOTIFICATION = "Permission denied while deleting notificaition"
  HTTP_182_DATABASE_NOT_FOUND = "Database Not found"
class SuccessCodes(Enum):
  HTTP_100_USER_FETCHED_SUCCESSFULLY = 100
  HTTP_104_USER_CREATED_SUCCESSFULLY = 104 #
  HTTP_107_USER_UPDATED_SUCCESSFULLY = 107 #
  HTTP_113_USER_DELETED_SUCCESSFULLY = 113 #
  HTTP_116_SUBSCRIPTION_DATA_FETCHED_SUCCESSFULLY = 116 #
  HTTP_119_SUBSCRIPTION_DATA_CREATED_SUCCESSFULLY = 119 #
  HTTP_123_SUBSCRIPTION_DATA_UPDATED_SUCCESSFULLY = 123 #
  HTTP_128_SUBSCRIPTION_DELETED_SUCCESSFULLY = 128 #
  HTTP_130_SUBSCRIPTION_PLAN_FETCHED_SUCCESSFULLY = 130 #
  HTTP_137_SUBSCRIPTION_PLAN_DELETED_SUCCESSFULLY = 137 #
  HTTP_133_SUBSCRIPTION_PLAN_CREATED_SUCCESSFULLY = 133
  HTTP_173_NOTIFICATION_CREATED_SUCCESSFULLY = 173
  HTTP_178_NOTIFICATION_DELETED_SUCCESSFULLY = 178
  
  
class SuccessCodeMessages(Enum):
  HTTP_100_USER_FETCHED_SUCCESSFULLY= "User Fetched Successfully"
  HTTP_104_USER_CREATED_SUCCESSFULLY = "User created Successfully"
  HTTP_107_USER_UPDATED_SUCCESSFULLY = "User updated successfully"
  HTTP_113_USER_DELETED_SUCCESSFULLY = "User deleted successfully"
  HTTP_116_SUBSCRIPTION_DATA_FETCHED_SUCCESSFULLY = "Subscription data fetched successfully"
  HTTP_119_SUBSCRIPTION_DATA_CREATED_SUCCESSFULLY = "Subscription data created successfully"
  HTTP_123_SUBSCRIPTION_DATA_UPDATED_SUCCESSFULLY = "Subscription data updated successfully"
  HTTP_128_SUBSCRIPTION_DELETED_SUCCESSFULLY = "Subscription deleted successfully"
  HTTP_130_SUBSCRIPTION_PLAN_FETCHED_SUCCESSFULLY = "Subscription_plan fetched successfully"
  HTTP_133_SUBSCRIPTION_PLAN_CREATED_SUCCESSFULLY = "Subscription_plan created successfully"
  HTTP_137_SUBSCRIPTION_PLAN_DELETED_SUCCESSFULLY = "Subscription_plan deleted successfully"
  HTTP_173_NOTIFICATION_CREATED_SUCCESSFULLY = "Notification created successfully"
  HTTP_178_NOTIFICATION_DELETED_SUCCESSFULLY = "Notification deleted successfully"
  